2025-06-23 07:11:28,673 INFO    Thread-8 (_run_job):954613 [wandb_setup.py:_flush():70] Current SDK version is 0.19.11
2025-06-23 07:11:28,673 INFO    Thread-8 (_run_job):954613 [wandb_setup.py:_flush():70] Configure stats pid to 954613
2025-06-23 07:11:28,673 INFO    Thread-8 (_run_job):954613 [wandb_setup.py:_flush():70] Loading settings from /home/cagri/.config/wandb/settings
2025-06-23 07:11:28,673 INFO    Thread-8 (_run_job):954613 [wandb_setup.py:_flush():70] Loading settings from /home/cagri/Desktop/IS-584-Term-Project/wandb/settings
2025-06-23 07:11:28,673 INFO    Thread-8 (_run_job):954613 [wandb_setup.py:_flush():70] Loading settings from environment variables
2025-06-23 07:11:28,673 INFO    Thread-8 (_run_job):954613 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /home/cagri/Desktop/IS-584-Term-Project/wandb/run-20250623_071128-3dhoba2c/logs/debug.log
2025-06-23 07:11:28,673 INFO    Thread-8 (_run_job):954613 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /home/cagri/Desktop/IS-584-Term-Project/wandb/run-20250623_071128-3dhoba2c/logs/debug-internal.log
2025-06-23 07:11:28,673 INFO    Thread-8 (_run_job):954613 [wandb_init.py:monkeypatch_ipython():643] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x726f0409bce0>
2025-06-23 07:11:28,673 INFO    Thread-8 (_run_job):954613 [wandb_init.py:init():852] calling init triggers
2025-06-23 07:11:28,673 INFO    Thread-8 (_run_job):954613 [wandb_init.py:init():857] wandb.init called with sweep_config: {'lora_alpha': 16, 'lora_dropout': 0.05, 'n_shots': 2, 'r': 2}
config: {'_wandb': {}}
2025-06-23 07:11:28,673 INFO    Thread-8 (_run_job):954613 [wandb_init.py:init():893] starting backend
2025-06-23 07:11:28,673 INFO    Thread-8 (_run_job):954613 [wandb_init.py:init():897] sending inform_init request
2025-06-23 07:11:28,674 INFO    Thread-8 (_run_job):954613 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-06-23 07:11:28,675 INFO    Thread-8 (_run_job):954613 [wandb_init.py:init():907] backend started and connected
2025-06-23 07:11:28,676 INFO    Thread-8 (_run_job):954613 [wandb_run.py:_config_callback():1436] config_cb None None {'lora_alpha': 16, 'lora_dropout': 0.05, 'n_shots': 2, 'r': 2}
2025-06-23 07:11:28,677 INFO    Thread-8 (_run_job):954613 [wandb_run.py:_label_probe_notebook():1376] probe notebook
2025-06-23 07:11:28,687 INFO    Thread-8 (_run_job):954613 [wandb_init.py:init():1005] updated telemetry
2025-06-23 07:11:28,689 INFO    Thread-8 (_run_job):954613 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-06-23 07:11:29,308 INFO    Thread-8 (_run_job):954613 [wandb_init.py:init():1104] starting run threads in backend
2025-06-23 07:11:29,402 INFO    Thread-8 (_run_job):954613 [wandb_run.py:_console_start():2573] atexit reg
2025-06-23 07:11:29,402 INFO    Thread-8 (_run_job):954613 [wandb_run.py:_redirect():2421] redirect: wrap_raw
2025-06-23 07:11:29,402 INFO    Thread-8 (_run_job):954613 [wandb_run.py:_redirect():2490] Wrapping output streams.
2025-06-23 07:11:29,402 INFO    Thread-8 (_run_job):954613 [wandb_run.py:_redirect():2513] Redirects installed.
2025-06-23 07:11:29,403 INFO    Thread-8 (_run_job):954613 [wandb_init.py:init():1150] run started, returning control to user process
2025-06-23 07:12:24,835 INFO    MainThread:954613 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-06-23 07:12:25,410 INFO    MsgRouterThr:954613 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-06-23 07:12:26,874 INFO    Thread-8 (_run_job):954613 [wandb_run.py:_finish():2321] finishing run e274028-metu-middle-east-technical-university/tinyllama-fewshot/3dhoba2c
2025-06-23 07:12:26,874 INFO    Thread-8 (_run_job):954613 [jupyter.py:save_history():477] not saving jupyter history
2025-06-23 07:12:26,874 INFO    Thread-8 (_run_job):954613 [jupyter.py:save_ipynb():401] not saving jupyter notebook
2025-06-23 07:12:26,874 INFO    Thread-8 (_run_job):954613 [wandb_init.py:_jupyter_teardown():628] cleaning up jupyter logic
2025-06-23 07:12:26,874 INFO    Thread-8 (_run_job):954613 [wandb_run.py:_atexit_cleanup():2538] got exitcode: 1
2025-06-23 07:12:26,874 INFO    Thread-8 (_run_job):954613 [wandb_run.py:_restore():2520] restore
2025-06-23 07:12:26,874 INFO    Thread-8 (_run_job):954613 [wandb_run.py:_restore():2526] restore done
2025-06-23 07:12:26,874 INFO    Thread-8 (_run_job):954613 [wandb_run.py:_restore():2520] restore
2025-06-23 07:12:26,874 INFO    Thread-8 (_run_job):954613 [wandb_run.py:_restore():2526] restore done
2025-06-23 07:12:26,874 ERROR   Thread-8 (_run_job):954613 [wandb_run.py:_atexit_cleanup():2559] Problem finishing run
Traceback (most recent call last):
  File "/home/cagri/.local/lib/python3.12/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
    self._function()
  File "/tmp/ipykernel_954613/3770935765.py", line 119, in sweep_prompt_eval
    evaluate(val_dataset, model, tokenizer, name="Validation")
  File "/tmp/ipykernel_954613/3770935765.py", line 34, in evaluate
    for batch in loader:
  File "/home/cagri/.local/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 733, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/cagri/.local/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 789, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cagri/.local/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/tmp/ipykernel_954613/563005050.py", line 32, in __getitem__
    prompt = build_few_shot_prompt(self.support_examples, query)
             ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'build_few_shot_prompt' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cagri/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2550, in _atexit_cleanup
    self._on_finish()
  File "/home/cagri/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2797, in _on_finish
    exit_handle = self._backend.interface.deliver_exit(self._exit_code)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cagri/.local/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 1005, in deliver_exit
    return self._deliver_exit(exit_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cagri/.local/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 436, in _deliver_exit
    return self._deliver_record(record)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cagri/.local/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 389, in _deliver_record
    handle = mailbox.require_response(record)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cagri/.local/lib/python3.12/site-packages/wandb/sdk/mailbox/mailbox.py", line 68, in require_response
    raise MailboxClosedError()
wandb.sdk.mailbox.mailbox.MailboxClosedError
